version: '3.7'

services:

  web: 
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    restart: unless-stopped
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media 
    env_file:
      - ./.env.prod
    links:
      - rabbit
    depends_on:
      - db 
      - rabbit

  react:
    build:
      context: ../auto-parser-front
      dockerfile: ./Dockerfile.prod
    env_file:
      - ../auto-parser-front/.env-prod
    volumes:
      - react_build:/app/build
    depends_on:
      - web

  rabbit:
    build: ./rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq/myrabbit.conf:/etc/rabbitmq/rabbitmq.config
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user_celery
      - RABBITMQ_DEFAULT_PASS=12re1QwS1eDsf1212 
    

  celery-parsing-worker:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A config worker -l info -c 40 -Q parsing_queue
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - ./.env.prod

  celery-beat-worker:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A config worker -l info -c 1 -Q beat_queue
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - ./.env.prod


  celery-beat:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A config beat
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - ./.env.prod



  flower:
    image: mher/flower:0.9.5
    command: [
      'flower',  
      '--broker=amqp://rabbit_user_celery:12re1QwS1eDsf1212@rabbit:5672//',
      '--broker_api=http://rabbit:15672/api//',
      '--port=5555', '--url_prefix=flower', 
      '--basic_auth=parserpaneladmin:nturjmkef94f98E21RKFOI43FM3F'
      ]
    restart: unless-stopped
    expose:
      - 5555
    depends_on:
      - rabbit
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: unless-stopped
    ports: 
      - 5432:5432


  nginx:
    build: ./nginx
    ports: 
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on: 
      - web
      - react
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media  
    - react_build:/app/build



volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build:
  rabbitmq_data:
  rabbitmq_logs: