version: '3.7'

services:

  web: 
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    links:
      - redis
    depends_on:
      - db 
      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=adw_dqwd12esd
      - POSTGRES_USER=auto_parser_user
      - POSTGRES_DB=auto_parser_db
      
  redis:
    image: redis:latest
    volumes:
      - redis_data:/redis/data
    ports:
      - 6379:6379

  celery:
      build: ./
      command: celery -A config worker -l info
      depends_on:
        - redis
      volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/media
      env_file:
        - ./.env.dev

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

