# Generated by Django 4.1 on 2022-08-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип прокси')),
                ('ip', models.CharField(max_length=255, verbose_name='IP прокси')),
                ('port', models.CharField(max_length=20, verbose_name='Порт прокси')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль прокси')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус привязан/не привязан')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('work', 'В работе'), ('blocked', 'В отстойнике'), ('paused', 'Не используется')], default='paused', max_length=255, verbose_name='Статус')),
                ('blocked', models.BooleanField(blank=True, null=True, verbose_name='Заблокирован')),
                ('blocked_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки')),
                ('block_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество блокировокк')),
                ('count_requests', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество сделаных запросов')),
                ('max_count_requests', models.PositiveIntegerField(default=950, verbose_name='Максимальное количество запросов')),
                ('proxy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.proxy', verbose_name='Прокси')),
            ],
        ),
    ]
