# Generated by Django 4.1 on 2022-08-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name': 'Прокси', 'verbose_name_plural': 'Прокси'},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
