# Generated by Django 4.1 on 2023-01-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0017_alter_parsertask_marker'),
        ('panel', '0003_proxy_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='proxy',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_parser.parsersite', verbose_name='Сайт аккаунта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='block_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество блокировок'),
        ),
    ]
