# Generated by Django 4.1 on 2023-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_siteuser_proxy_siteuser_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус работает или нет'),
        ),
    ]