# Generated by Django 4.1 on 2023-06-27 10:56

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_proxy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='isUsed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Использовано'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='request_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество запросов с прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус вкл/выкл'),
        ),
    ]
