# Generated by Django 4.1 on 2023-07-04 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_proxy_isused_proxy_request_count_alter_proxy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='request_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время последнего использования прокси'),
            preserve_default=False,
        ),
    ]