version: '3'

services:
  auto-parser:
    image: auto-parser-front-prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./.env-prod
    ports:
      - 8080:80



