# Generated by Django 4.1 on 2022-08-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserInputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='', verbose_name='Входящие данные парсера')),
            ],
            options={
                'verbose_name': 'Файл входных данных',
                'verbose_name_plural': 'Файлы фходных данных',
            },
        ),
        migrations.CreateModel(
            name='ParserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(upload_to='', verbose_name='Выходящие данные парсера')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paused', 'Пауза'), ('run', 'Выполняется'), ('canceled', 'Отменен'), ('done', 'Выполнен')], default='run', max_length=255, verbose_name='Статус работы парсера')),
                ('input_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_parser.parserinputfile', verbose_name='Входные данные')),
            ],
            options={
                'verbose_name': 'Задача парсер',
                'verbose_name_plural': 'Задачи парсер',
            },
        ),
    ]
