# Generated by Django 4.1 on 2022-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0002_remove_parserinputfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='status',
            field=models.CharField(choices=[('paused', 'Пауза'), ('run', 'Выполняется'), ('canceled', 'Отменен'), ('done', 'Выполнен')], default='paused', max_length=255, verbose_name='Статус работы парсера'),
        ),
    ]
