# Generated by Django 4.1 on 2022-08-16 22:16

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0003_alter_parsertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserinputfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=src.base.services.get_path_upload_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Входящие данные парсера'),
        ),
    ]
