# Generated by Django 4.1 on 2022-08-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0005_parsertask_rows_count_alter_parsertask_output_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserinputfile',
            options={'verbose_name': 'Файл входных данных', 'verbose_name_plural': 'Файлы входных данных'},
        ),
        migrations.AlterField(
            model_name='parsertask',
            name='input_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='my_parser.parserinputfile', verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='parsertask',
            name='output_file',
            field=models.FilePathField(blank=True, null=True, path='/media/output_files/', verbose_name='Выходящие данные парсера'),
        ),
    ]
