# Generated by Django 4.1 on 2022-08-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0006_alter_parserinputfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='output_file',
            field=models.FilePathField(blank=True, null=True, path='media/output_files/', verbose_name='Выходящие данные парсера'),
        ),
    ]
