# Generated by Django 4.1 on 2022-08-18 21:00

from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0007_alter_parsertask_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=src.base.services.get_path_output_file, verbose_name='Выходящие данные парсера'),
        ),
    ]
