# Generated by Django 4.1 on 2022-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0008_alter_parsertask_output_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserFindItem',
            fields=[
                ('offer_key', models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True, verbose_name='Индивидуальный ключ товара')),
                ('rating', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Рейтинг')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Наличие')),
                ('delivery', models.IntegerField(blank=True, null=True, verbose_name='Срок доставки')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Выходные данные задачи',
                'verbose_name_plural': 'Выходные данные задачи',
            },
        ),
        migrations.CreateModel(
            name='ParserOutputTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Брэнд')),
                ('finds_list', models.ManyToManyField(related_query_name='finds_list', to='my_parser.parserfinditem', verbose_name='Список найденных предложений')),
            ],
            options={
                'verbose_name': 'Выходные данные задачи',
                'verbose_name_plural': 'Выходные данные задачи',
            },
        ),
    ]
