# Generated by Django 4.1 on 2022-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0009_parserfinditem_parseroutputtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseroutputtask',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='parseroutputtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы парсера'),
        ),
    ]
