# Generated by Django 4.1 on 2022-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0010_parseroutputtask_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserfinditem',
            options={'verbose_name': 'Оффер задачи', 'verbose_name_plural': 'Оффер задачи'},
        ),
        migrations.AddField(
            model_name='parseroutputtask',
            name='arrival_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена прихода'),
        ),
        migrations.AddField(
            model_name='parseroutputtask',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='parseroutputtask',
            name='free_balance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Свободный остаток'),
        ),
        migrations.AddField(
            model_name='parseroutputtask',
            name='stock',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Склад'),
        ),
    ]
