# Generated by Django 4.1 on 2022-10-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0011_alter_parserfinditem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsertask',
            name='output_file',
        ),
    ]
