# Generated by Django 4.1 on 2022-11-11 14:25

from django.db import migrations, models
import src.my_parser.utils


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0013_parseroutputtask_holding_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сайта')),
            ],
            options={
                'verbose_name': 'Сайт для парсинга',
                'verbose_name_plural': 'Сайты для парсинга',
            },
        ),
        migrations.AlterField(
            model_name='parseroutputtask',
            name='finds_list',
            field=models.ManyToManyField(to='my_parser.parserfinditem', verbose_name='Список найденных предложений'),
        ),
        migrations.AddField(
            model_name='parsertask',
            name='sites',
            field=models.ManyToManyField(blank=True, default=src.my_parser.utils.firstParserSite, to='my_parser.parsersite', verbose_name='Сайты для парсинга'),
        ),
    ]
