# Generated by Django 4.1 on 2023-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0016_parseroutputtask_task_marker_parsertask_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='marker',
            field=models.CharField(choices=[('1', 'Аналитика'), ('2', 'Наличие'), ('3', 'Техническое')], default='1', max_length=2, verbose_name='Маркер'),
        ),
    ]
