# Generated by Django 4.1 on 2023-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0017_alter_parsertask_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsersite',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Сайт вкл/выкл'),
        ),
    ]
