# Generated by Django 4.1 on 2023-03-27 11:20

from django.db import migrations, models
import django.db.models.deletion
import src.my_parser.utils


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0018_parsersite_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataArray',
            fields=[
                ('parseroutputtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_parser.parseroutputtask')),
            ],
            options={
                'verbose_name': 'Массив входных данных',
                'verbose_name_plural': 'Массив входных данных',
            },
            bases=('my_parser.parseroutputtask',),
        ),
        migrations.AlterField(
            model_name='parseroutputtask',
            name='finds_list',
            field=models.ManyToManyField(blank=True, null=True, to='my_parser.parserfinditem', verbose_name='Список найденных предложений'),
        ),
        migrations.CreateModel(
            name='ParserTaskFromArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('marker', models.CharField(choices=[('1', 'Аналитика'), ('2', 'Наличие'), ('3', 'Техническое')], default='1', max_length=2, verbose_name='Маркер')),
                ('rows_count', models.IntegerField(blank=True, default=0, verbose_name='Количество заданий')),
                ('status', models.CharField(choices=[('ready', 'Готов к выполнению'), ('run', 'Выполняется'), ('done', 'Выполнен')], default='ready', max_length=255, verbose_name='Статус работы парсера')),
                ('input_data', models.ManyToManyField(to='my_parser.inputdataarray', verbose_name='Массив входных данных')),
                ('sites', models.ManyToManyField(blank=True, default=src.my_parser.utils.firstParserSite, to='my_parser.parsersite', verbose_name='Сайты для парсинга')),
            ],
            options={
                'verbose_name': 'Задача парсер из массива',
                'verbose_name_plural': 'Задачи парсер из массива',
            },
        ),
    ]