# Generated by Django 4.1 on 2023-06-27 10:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0019_inputdataarray_alter_parseroutputtask_finds_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsertask',
            name='marker',
            field=models.CharField(choices=[('1', 'Аналитика'), ('2', 'Наличие'), ('3', 'API'), ('4', 'Техническое')], default='1', max_length=2, verbose_name='Маркер'),
        ),
    ]
